### ISSUE TITLE
Yeelight bulb RGB v2 problem

### ISSUE THREAD

**Issue by CSC11** [iobroker-community-adapters/ioBroker.yeelight-2#8]
2018-09-09 18:25:16.282  - info: yeelight-2.0 terminating
--
2018-09-09 18:25:16.308  - error: Caught by controller[0]: TypeError: Cannot read property 'val' of null
2018-09-09 18:25:16.309  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.yeelight-2/main.js:190:59
2018-09-09 18:25:16.310  - error:  Caught by controller[0]:     at Command.callback  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:287:17)
2018-09-09 18:25:16.310  - error: Caught by controller[0]:     at normal_reply (/opt/iobroker/node_modules/redis/index.js:726:21)
2018-09-09 18:25:16.311  - error: Caught by controller[0]:     at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:824:9)
2018-09-09 18:25:16.311  - error: Caught by controller[0]:     at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
2018-09-09 18:25:16.312  - error: Caught by controller[0]:     at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:574:12)
2018-09-09 18:25:16.312  - error: Caught by controller[0]:     at Socket. (/opt/iobroker/node_modules/redis/index.js:274:27)
2018-09-09 18:25:16.312  - error: Caught by controller[0]:     at emitOne (events.js:96:13)
2018-09-09 18:25:16.313  - error: Caught by controller[0]:     at Socket.emit (events.js:188:7)
2018-09-09 18:25:16.313  - error: Caught by controller[0]:     at readableAddChunk (_stream_readable.js:176:18)
2018-09-09 18:25:16.314  - error: host.ioBroker-Pi instance system.adapter.yeelight-2.0 terminated with code 0 (OK)
2018-09-09 18:25:16.314  - info: host.ioBroker-Pi Restart adapter system.adapter.yeelight-2.0 because enabled

**Comment by MeisterTR** [comment]
how does your config look like?

**Comment by CSC11** [comment]
IP der Lampe von fritzbox heraus gesucht und eingetragen, Port 55443... Bezeichnungen bzw. Smarthome Name sind ja willkürlich...

**Comment by MeisterTR** [comment]
ne willkürlich sind sie nicht. schalte den adapter mal bitte auf debug um und poste nochmal das log. Hast du die Lampe über die suchfunktion hinzugefügt?

**Comment by CSC11** [comment]
Das oben ist der log der erzeugt wurde wie die Lampe auf debug geschaltet worden ist.

Automatisch finden hat auch nicht funktioniert habe dann die Lampe manuell hinzu gefügt.

**Comment by MeisterTR** [comment]
hast du unter den objekten unter info.ip und info.com was stehen?

**Comment by CSC11** [comment]
Ich werde nachsehen sobald ich heute Nachmittag von der Arbeit zuhause bin. Danke derweil schonmal :)

**Comment by CSC11** [comment]
Also ich habe nachgesehen, ich habe keinelei Werte bei den einzelnen Objekten. Hier ist alles leer.
![grafik](https://user-images.githubusercontent.com/43115772/45302273-21bf6e80-b513-11e8-9fc4-4e53c96aaa50.png)

**Comment by MeisterTR** [comment]
das ist merkwürdig, lösche mal die lampe aus den objekten und starte den adapter neu

**Comment by CSC11** [comment]
Servus,
die Adapter und Instanzen habe ich schon 20 mal gelöscht und wieder installiert keine Besserung.
Aber ich habe das Problem gefunden aber keine Ahnung warum es so ist... 

Ich habe den Lampen eine neue IP zugewiesen... Zack und schon funktioniert alles wie es soll... Frage mich nur warum...

Aber danke dir wirklich für deine schnelle Hilfe!
